[[WiringPi]]
arch = "aarch64"
git-tree-sha1 = "dea4a276fb1b23911559634016f1f15f59d8bc49"
libc = "glibc"
os = "linux"

    [[WiringPi.download]]
    sha256 = "a353c9dd9b8df22d08677bf06a69b89bdceb9331cf65b6508825d2361b078643"
    url = "https://github.com/JuliaBinaryWrappers/WiringPi_jll.jl/releases/download/WiringPi-v3.16.0+0/WiringPi.v3.16.0.aarch64-linux-gnu.tar.gz"
