# Autogenerated wrapper script for WiringPi_jll for aarch64-linux-gnu
export wiringPi

JLLWrappers.@generate_wrapper_header("WiringPi")
JLLWrappers.@declare_library_product(wiringPi, "libwiringPi.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        wiringPi,
        "lib/libwiringPi.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
